[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
#runner = "probe-rs run --chip esp32-3.3v"

[env]
ESP_LOGLEVEL = "TRACE"

[build]
rustflags = [
  "-C",
  "link-arg=-nostartfiles",
  "-C",
  "link-arg=-Wl,-Tlinkall.x",

  # for esp-wifi
  "-C",
  "link-arg=-Trom_functions.x",

  # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
  # NOTE: May negatively impact performance of produced code
  # "-C",
  # "force-frame-pointers",
]

target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["core", "alloc"]
